Add a logic to check if High risk alerts are more than 1

diff --git a/.github/workflows/zap-pen-test.yaml b/.github/workflows/zap-pen-test.yaml
--- a/.github/workflows/zap-pen-test.yaml
+++ b/.github/workflows/zap-pen-test.yaml
@@ -16,8 +16,16 @@ jobs:
 
     - name: Execute baseline scan
       run: docker run -v /report:/zap/wrk/:rw --user root -t zaproxy/zap-weekly zap-baseline.py -t ${{env.URI}} -I -r zap-report.html
+
+    - name: Check for high-severity alerts
+      run: |    
+        HIGH_ALERTS=$(grep -o '"risk":"High"' /report/zap-report.html | wc -l)  # This will check the report and if the high risk alerts are greater than 1 it will fail the job
+        if [ "$HIGH_ALERTS" -gt 1 ]; then
+          exit 1  # This causes the job to fail
+        fi
   
     - uses: actions/upload-artifact@v4
+      if: always()  # Upload the report even if the check above failed
       name: upload OWASP ZAP report
       with:
         name: OWASP ZAP Report
